(setq backup-directory-alist '(("." . "~/.emacs_backups")))
(setq initial-scratch-message (insert-file-contents "~/emacs-config/note.txt"))
(setq-default fill-column 100)
(global-display-fill-column-indicator-mode)
(add-hook 'window-setup-hook 'toggle-frame-maximized)
(add-hook 'prog-mode-hook 'hs-minor-mode)
(setq c-basic-offset 4)
(setq default-tab-width 4)
(setq c-default-style "bsd")
(setq-default indent-tabs-mode nil)
(add-hook 'prog-mode-hook (lambda () (local-set-key (kbd "<f5>") 'quickrun-shell)))
(setq inferior-lisp-program "sbcl")
